# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tav/Git/Thermopylae

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tav/Git/Thermopylae

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tav/Git/Thermopylae/CMakeFiles /home/tav/Git/Thermopylae/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tav/Git/Thermopylae/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FRC_UserProgram.out

# Build rule for target.
FRC_UserProgram.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FRC_UserProgram.out
.PHONY : FRC_UserProgram.out

# fast build rule for target.
FRC_UserProgram.out/fast:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/build
.PHONY : FRC_UserProgram.out/fast

Autonomous.obj: Autonomous.cpp.obj
.PHONY : Autonomous.obj

# target to build an object file
Autonomous.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Autonomous.cpp.obj
.PHONY : Autonomous.cpp.obj

Autonomous.i: Autonomous.cpp.i
.PHONY : Autonomous.i

# target to preprocess a source file
Autonomous.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Autonomous.cpp.i
.PHONY : Autonomous.cpp.i

Autonomous.s: Autonomous.cpp.s
.PHONY : Autonomous.s

# target to generate assembly for a file
Autonomous.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Autonomous.cpp.s
.PHONY : Autonomous.cpp.s

Disabled.obj: Disabled.cpp.obj
.PHONY : Disabled.obj

# target to build an object file
Disabled.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Disabled.cpp.obj
.PHONY : Disabled.cpp.obj

Disabled.i: Disabled.cpp.i
.PHONY : Disabled.i

# target to preprocess a source file
Disabled.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Disabled.cpp.i
.PHONY : Disabled.cpp.i

Disabled.s: Disabled.cpp.s
.PHONY : Disabled.s

# target to generate assembly for a file
Disabled.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Disabled.cpp.s
.PHONY : Disabled.cpp.s

OperatorControl.obj: OperatorControl.cpp.obj
.PHONY : OperatorControl.obj

# target to build an object file
OperatorControl.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OperatorControl.cpp.obj
.PHONY : OperatorControl.cpp.obj

OperatorControl.i: OperatorControl.cpp.i
.PHONY : OperatorControl.i

# target to preprocess a source file
OperatorControl.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OperatorControl.cpp.i
.PHONY : OperatorControl.cpp.i

OperatorControl.s: OperatorControl.cpp.s
.PHONY : OperatorControl.s

# target to generate assembly for a file
OperatorControl.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OperatorControl.cpp.s
.PHONY : OperatorControl.cpp.s

OurRobot.obj: OurRobot.cpp.obj
.PHONY : OurRobot.obj

# target to build an object file
OurRobot.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OurRobot.cpp.obj
.PHONY : OurRobot.cpp.obj

OurRobot.i: OurRobot.cpp.i
.PHONY : OurRobot.i

# target to preprocess a source file
OurRobot.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OurRobot.cpp.i
.PHONY : OurRobot.cpp.i

OurRobot.s: OurRobot.cpp.s
.PHONY : OurRobot.s

# target to generate assembly for a file
OurRobot.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OurRobot.cpp.s
.PHONY : OurRobot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... FRC_UserProgram.out"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Autonomous.obj"
	@echo "... Autonomous.i"
	@echo "... Autonomous.s"
	@echo "... Disabled.obj"
	@echo "... Disabled.i"
	@echo "... Disabled.s"
	@echo "... OperatorControl.obj"
	@echo "... OperatorControl.i"
	@echo "... OperatorControl.s"
	@echo "... OurRobot.obj"
	@echo "... OurRobot.i"
	@echo "... OurRobot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

